import Constants from 'expo-constants';
import { Platform } from 'react-native';

import { speakAidaText, testAidaSpeech } from '@/src/core/interaction/speech-output';
import { MOBILE_REASONING } from '@/src/core/reasoning/service';
import {
  loadActivity,
  loadOrCreateInstanceId,
  loadRuntimeState,
  saveActivity,
  saveRuntimeState,
} from '@/src/core/storage/mobile-storage';

export type StatusTone = 'ready' | 'active' | 'warning' | 'error' | 'idle' | 'offline';
export type LocalRuntimeStatus = 'STARTING' | 'STANDBY' | 'ANALYZING' | 'WARNING' | 'ERROR';

export type SubsystemStatus = { id: string; label: string; value: string; tone: StatusTone };
export type RuntimeCapability = {
  id: string;
  label: string;
  state: 'supported' | 'limited' | 'staged';
  detail: string;
};
export type RuntimeActivityItem = {
  id: string;
  category: string;
  message: string;
  severity: 'info' | 'warning' | 'error';
  source: string;
  created_at: string;
};
export type MobileRuntimeSnapshot = {
  instance_id: string;
  identity_persistent: boolean;
  runtime_mode: 'standalone';
  status: LocalRuntimeStatus;
  platform: string;
  platform_version: string;
  device_model: string;
  app_version: string;
  initialized_at: string;
  updated_at: string;
  speech_enabled: boolean;
  autonomy: { enabled: boolean; label: string };
  statuses: SubsystemStatus[];
  capabilities: RuntimeCapability[];
};

type RuntimeListener = (snapshot: MobileRuntimeSnapshot) => void;
type ActivityListener = (items: RuntimeActivityItem[]) => void;

let snapshot = createStartingSnapshot();
let activity: RuntimeActivityItem[] = [];
let initialization: Promise<MobileRuntimeSnapshot> | null = null;
const runtimeListeners = new Set<RuntimeListener>();
const activityListeners = new Set<ActivityListener>();

export function getRuntimeSnapshot(): MobileRuntimeSnapshot {
  void initializeAidaRuntime();
  return snapshot;
}

export async function initializeAidaRuntime(): Promise<MobileRuntimeSnapshot> {
  if (initialization) return initialization;
  initialization = hydrateRuntime();
  return initialization;
}

export function getRuntimeActivity(limit = 30): RuntimeActivityItem[] {
  void initializeAidaRuntime();
  return activity.slice(0, Math.max(1, Math.min(100, Math.trunc(limit))));
}

export function subscribeRuntime(listener: RuntimeListener): () => void {
  runtimeListeners.add(listener);
  listener(snapshot);
  void initializeAidaRuntime();
  return () => runtimeListeners.delete(listener);
}

export function subscribeRuntimeActivity(listener: ActivityListener): () => void {
  activityListeners.add(listener);
  listener([...activity]);
  void initializeAidaRuntime();
  return () => activityListeners.delete(listener);
}

export async function setSpeechEnabled(enabled: boolean): Promise<void> {
  await initializeAidaRuntime();
  snapshot = {
    ...snapshot,
    speech_enabled: enabled,
    updated_at: new Date().toISOString(),
    statuses: snapshot.statuses.map((item) =>
      item.id === 'speech'
        ? { ...item, value: enabled ? 'TESTING' : 'MUTED', tone: enabled ? 'active' : 'idle' }
        : item,
    ),
  };
  notifyRuntime();
  await saveRuntimeState({
    autonomy_enabled: snapshot.autonomy.enabled,
    speech_enabled: enabled,
  });
  await addActivity(
    'SPEECH',
    enabled ? 'AIDA speech output enabled.' : 'AIDA speech output muted.',
    'info',
    'mobile.speech',
  );

  if (enabled) {
    await testAidaSpeech({
      onStart: () => setSubsystemStatus('speech', 'SPEAKING', 'active'),
      onDone: () => setSubsystemStatus('speech', 'READY', 'ready'),
      onError: (message) => {
        setSubsystemStatus('speech', 'ERROR', 'warning');
        void addActivity('SPEECH', `Speech self-test failed: ${message}`, 'warning', 'mobile.speech');
      },
    });
  }
}

export async function submitLocalDirective(message: string): Promise<string> {
  await initializeAidaRuntime();
  const clean = message.trim();
  if (!clean) throw new Error('Directive cannot be empty.');

  const remote = MOBILE_REASONING.isRemoteConfigured();
  setAgentState('ANALYZING', remote ? 'REASONING' : 'LOCAL', 'active');
  await addActivity('DIRECTIVE', 'Local directive received.', 'info', 'mobile.runtime');

  const response = await MOBILE_REASONING.respond(clean, {
    platform: snapshot.platform,
    platformVersion: snapshot.platform_version,
    deviceModel: snapshot.device_model,
    instanceId: snapshot.instance_id,
    supportedCapabilities: snapshot.capabilities
      .filter((item) => item.state === 'supported')
      .map((item) => item.label),
  });

  await addActivity(
    'AIDA',
    `Response generated by ${response.provider} (${response.mode}).`,
    'info',
    response.provider,
  );
  setAgentState('STANDBY', response.mode === 'remote' ? 'READY' : 'STAGED', 'ready');
  void speakResponseIfEnabled(response.text);
  return response.text;
}

async function hydrateRuntime(): Promise<MobileRuntimeSnapshot> {
  const platform = platformLabel();
  const model = deviceModel();
  try {
    const [identity, state, storedActivity] = await Promise.all([
      loadOrCreateInstanceId(Platform.OS),
      loadRuntimeState(),
      loadActivity<RuntimeActivityItem>(),
    ]);
    await MOBILE_REASONING.initialize();

    activity = storedActivity.slice(0, 100);
    const gatewayReady = MOBILE_REASONING.isRemoteConfigured();
    const now = new Date().toISOString();
    snapshot = {
      instance_id: identity.instanceId,
      identity_persistent: true,
      runtime_mode: 'standalone',
      status: 'STANDBY',
      platform,
      platform_version: String(Platform.Version),
      device_model: model,
      app_version: Constants.expoConfig?.version ?? '0.1.0',
      initialized_at: now,
      updated_at: now,
      speech_enabled: state.speech_enabled,
      autonomy: {
        enabled: state.autonomy_enabled,
        label: state.autonomy_enabled ? 'ENABLED' : 'LOCAL SAFE MODE',
      },
      statuses: [
        status('agent', 'AGENT', 'STANDBY', 'ready'),
        status('brain', 'BRAIN', gatewayReady ? 'READY' : 'STAGED', gatewayReady ? 'ready' : 'idle'),
        status('speech', 'SPEECH', state.speech_enabled ? 'READY' : 'MUTED', state.speech_enabled ? 'ready' : 'idle'),
        status('diagnostics', 'DIAGNOSTICS', 'READY', 'ready'),
        status('memory', 'MEMORY', 'READY', 'ready'),
        status('artificer', 'ARTIFICER', 'STAGED', 'idle'),
        status('technomancer', 'TECHNOMANCER', 'STAGED', 'idle'),
        status('perception', 'PERCEPTION', 'STAGED', 'idle'),
        status('microphone', 'MICROPHONE', 'STAGED', 'idle'),
        status('tasks', 'TASKS', '0 ACTIVE', 'idle'),
        status('platform', 'PLATFORM', platform.toUpperCase(), 'ready'),
      ],
      capabilities: buildCapabilities(platform, gatewayReady),
    };

    await addActivity(
      'RUNTIME',
      identity.created
        ? `Created persistent AIDA instance ${identity.instanceId} on ${platform} ${String(Platform.Version)} (${model}).`
        : `Restored persistent AIDA instance ${identity.instanceId} on ${platform} ${String(Platform.Version)} (${model}).`,
      'info',
      'mobile.runtime',
    );
    notifyRuntime();
    return snapshot;
  } catch (error) {
    const detail = error instanceof Error ? error.message : 'Unknown storage error';
    snapshot = {
      ...snapshot,
      status: 'WARNING',
      updated_at: new Date().toISOString(),
      statuses: snapshot.statuses.map((item) =>
        item.id === 'memory'
          ? { ...item, value: 'DEGRADED', tone: 'warning' as const }
          : item.id === 'agent'
            ? { ...item, value: 'WARNING', tone: 'warning' as const }
            : item,
      ),
    };
    await addActivity(
      'STORAGE',
      `Persistent mobile storage initialization failed: ${detail}`,
      'warning',
      'mobile.storage',
      false,
    );
    notifyRuntime();
    return snapshot;
  }
}

async function speakResponseIfEnabled(text: string) {
  if (!snapshot.speech_enabled) return;
  await speakAidaText(text, {
    onStart: () => setSubsystemStatus('speech', 'SPEAKING', 'active'),
    onDone: () => setSubsystemStatus('speech', 'READY', 'ready'),
    onError: (message) => {
      setSubsystemStatus('speech', 'ERROR', 'warning');
      void addActivity('SPEECH', `Speech output failed: ${message}`, 'warning', 'mobile.speech');
    },
  });
}

function setSubsystemStatus(id: string, value: string, tone: StatusTone) {
  snapshot = {
    ...snapshot,
    updated_at: new Date().toISOString(),
    statuses: snapshot.statuses.map((item) =>
      item.id === id ? { ...item, value, tone } : item,
    ),
  };
  notifyRuntime();
}

function buildCapabilities(platform: string, gatewayReady: boolean): RuntimeCapability[] {
  return [
    { id: 'runtime.local', label: 'Local AIDA runtime', state: 'supported', detail: 'AIDA initializes and maintains runtime state on this device without a desktop bridge.' },
    { id: 'identity.persistent', label: 'Persistent instance identity', state: 'supported', detail: 'This AIDA instance retains a secure device-local identity across application restarts.' },
    { id: 'platform.identity', label: 'Platform awareness', state: 'supported', detail: `AIDA identifies this host as ${platform} ${String(Platform.Version)}.` },
    { id: 'conversation.local', label: 'Local directive intake', state: 'supported', detail: 'The mobile runtime accepts directives locally and routes them through the configured reasoning provider.' },
    { id: 'activity.persistent', label: 'Persistent activity journal', state: 'supported', detail: 'Runtime activity is stored locally and restored when this mobile AIDA instance starts again.' },
    { id: 'memory.persistent', label: 'Persistent mobile storage', state: 'supported', detail: 'AIDA has persistent local runtime storage; the full semantic memory layer remains a later milestone.' },
    { id: 'reasoning.provider', label: 'Reasoning provider interface', state: 'supported', detail: `AIDA currently uses ${MOBILE_REASONING.currentProviderId()} and can switch providers without changing the frontend.` },
    { id: 'reasoning.gateway', label: 'AIDA reasoning gateway', state: gatewayReady ? 'supported' : 'staged', detail: gatewayReady ? 'Authenticated independent reasoning is configured for this mobile AIDA instance.' : 'Independent reasoning remains staged until enrollment supplies a secure gateway session credential.' },
    { id: 'speech.output', label: 'AIDA speech output', state: 'supported', detail: 'AIDA can speak responses through the mobile operating system speech service.' },
    { id: 'voice.input', label: 'Voice input and transcription', state: 'staged', detail: 'Microphone capture and transcription remain staged until the secure transcription path is connected.' },
  ];
}

function createStartingSnapshot(): MobileRuntimeSnapshot {
  const now = new Date().toISOString();
  const platform = platformLabel();
  return {
    instance_id: 'initializing',
    identity_persistent: false,
    runtime_mode: 'standalone',
    status: 'STARTING',
    platform,
    platform_version: String(Platform.Version),
    device_model: deviceModel(),
    app_version: Constants.expoConfig?.version ?? '0.1.0',
    initialized_at: now,
    updated_at: now,
    speech_enabled: false,
    autonomy: { enabled: false, label: 'LOCAL SAFE MODE' },
    statuses: [
      status('agent', 'AGENT', 'STARTING', 'active'),
      status('brain', 'BRAIN', 'STAGED', 'idle'),
      status('speech', 'SPEECH', 'MUTED', 'idle'),
      status('diagnostics', 'DIAGNOSTICS', 'STARTING', 'active'),
      status('memory', 'MEMORY', 'LOADING', 'active'),
      status('artificer', 'ARTIFICER', 'STAGED', 'idle'),
      status('technomancer', 'TECHNOMANCER', 'STAGED', 'idle'),
      status('perception', 'PERCEPTION', 'STAGED', 'idle'),
      status('microphone', 'MICROPHONE', 'STAGED', 'idle'),
      status('tasks', 'TASKS', '0 ACTIVE', 'idle'),
      status('platform', 'PLATFORM', platform.toUpperCase(), 'ready'),
    ],
    capabilities: [],
  };
}

function setAgentState(next: LocalRuntimeStatus, brainValue: string, agentTone: StatusTone) {
  snapshot = {
    ...snapshot,
    status: next,
    updated_at: new Date().toISOString(),
    statuses: snapshot.statuses.map((item) => {
      if (item.id === 'agent') return { ...item, value: next, tone: agentTone };
      if (item.id === 'brain') {
        return {
          ...item,
          value: brainValue,
          tone:
            brainValue === 'REASONING' || brainValue === 'LOCAL'
              ? ('active' as const)
              : brainValue === 'READY'
                ? ('ready' as const)
                : ('idle' as const),
        };
      }
      return item;
    }),
  };
  notifyRuntime();
}

async function addActivity(category: string, message: string, severity: RuntimeActivityItem['severity'], source: string, persist = true) {
  const item: RuntimeActivityItem = {
    id: `activity-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    category,
    message,
    severity,
    source,
    created_at: new Date().toISOString(),
  };
  activity = [item, ...activity].slice(0, 100);
  notifyActivity();
  if (persist) {
    try {
      await saveActivity(activity);
    } catch {
      // Runtime operation must not fail merely because activity persistence did.
    }
  }
}

function notifyRuntime() {
  for (const listener of runtimeListeners) listener(snapshot);
}

function notifyActivity() {
  const copy = [...activity];
  for (const listener of activityListeners) listener(copy);
}

function status(id: string, label: string, value: string, tone: StatusTone): SubsystemStatus {
  return { id, label, value, tone };
}

function platformLabel() {
  if (Platform.OS === 'android') return 'Android';
  if (Platform.OS === 'ios') return 'iOS';
  return Platform.OS;
}

function deviceModel() {
  const constants = Platform.constants as { Model?: string };
  return constants?.Model?.trim() || `${platformLabel()} device`;
}
