from __future__ import annotations

from aida.intent.models import IntentDefinition, IntentRisk
from aida.intent.registry import IntentRegistry


def register_early_alpha_intents(registry: IntentRegistry) -> IntentRegistry:
    definitions = (
        IntentDefinition(
            intent_id="security.scan.intelligent",
            command_type="SECURITY_INTELLIGENT_SCAN",
            actions=frozenset(
                {
                    "run",
                    "start",
                    "perform",
                    "begin",
                    "launch",
                    "execute",
                    "do",
                    "check",
                    "scan",
                }
            ),
            objects=frozenset(
                {
                    "intelligent security scan",
                    "intelligent scan",
                    "adaptive security scan",
                    "adaptive scan",
                    "smart security scan",
                    "smart scan",
                    "aegis scan",
                    "aegis security scan",
                    "security scan",
                    "malware scan",
                    "virus scan",
                    "antivirus scan",
                    "anti virus scan",
                    "malware",
                    "viruses",
                    "threats",
                }
            ),
            modifiers=frozenset(
                {
                    "intelligent",
                    "adaptive",
                    "smart",
                    "aegis",
                    "security",
                }
            ),
            aliases=frozenset(
                {
                    "intelligent security scan",
                    "run intelligent security scan",
                    "run an intelligent security scan",
                    "start intelligent security scan",
                    "start an intelligent security scan",
                    "adaptive security scan",
                    "run adaptive security scan",
                    "aegis adaptive scan",
                    "run aegis adaptive scan",
                    "smart security scan",
                    "run aegis scan",
                    "aegis security scan",
                    "run a security scan",
                    "run security scan",
                    "check my computer for malware",
                    "check my pc for malware",
                    "scan my computer for viruses",
                    "scan my pc for viruses",
                    "check for malware",
                    "check for viruses",
                    "check for threats",
                }
            ),
            negative_terms=frozenset(
                {
                    "full system",
                    "full sweep",
                    "deep",
                    "targeted",
                    "surface",
                    "low level",
                    "quick malware",
                    "quick security",
                }
            ),
            risk=IntentRisk.LOW_OPERATIONAL,
            local_only=True,
            description="an Aegis Adaptive Security Scan",
            priority=124,
        ),
        IntentDefinition(
            intent_id="security.threat.analyze",
            command_type="THREAT_ANALYZE",
            actions=frozenset({"analyze", "inspect", "review", "assess"}),
            objects=frozenset({"threat", "suspicious file", "detected file", "file"}),
            aliases=frozenset({"analyze threat", "analyze suspicious file", "inspect detected file", "reanalyze threat"}),
            required_slots=("target_path",),
            risk=IntentRisk.INFORMATIONAL,
            local_only=True,
            description="read-only local threat analysis",
            priority=119,
        ),
        IntentDefinition(
            intent_id="navigation.evidence.locate",
            command_type="EVIDENCE_LOCATE",
            actions=frozenset({"locate", "find", "search"}),
            objects=frozenset({"threat file", "detected file", "reported file", "evidence", "file"}),
            aliases=frozenset({"locate threat file", "find detected file", "find that threat", "locate reported item"}),
            required_slots=("target_path",),
            risk=IntentRisk.INFORMATIONAL,
            local_only=True,
            description="bounded evidence-location search",
            priority=116,
        ),
        IntentDefinition(
            intent_id="navigation.evidence.open",
            command_type="EVIDENCE_OPEN_FOLDER",
            actions=frozenset({"open", "show"}),
            objects=frozenset({"containing folder", "folder", "file location", "threat location"}),
            aliases=frozenset({"open containing folder", "show threat location", "open the folder containing the threat"}),
            required_slots=("target_path",),
            risk=IntentRisk.INFORMATIONAL,
            local_only=True,
            description="open the containing folder without executing the target",
            priority=114,
        ),
        IntentDefinition(
            intent_id="navigation.evidence.select",
            command_type="EVIDENCE_SELECT",
            actions=frozenset({"select", "show"}),
            objects=frozenset({"file explorer", "explorer", "detected file", "threat file"}),
            aliases=frozenset({"select in explorer", "show file in explorer", "select threat file"}),
            required_slots=("target_path",),
            risk=IntentRisk.INFORMATIONAL,
            local_only=True,
            description="select the exact file in Explorer without opening it",
            priority=115,
        ),
        IntentDefinition(
            intent_id="security.threat.response_plan",
            command_type="THREAT_RESPONSE_PLAN",
            actions=frozenset({"prepare", "create", "show", "review"}),
            objects=frozenset({"threat response", "response plan", "remediation plan", "threat plan"}),
            aliases=frozenset({"prepare threat response", "create threat response plan", "show remediation plan"}),
            required_slots=("target_path",),
            risk=IntentRisk.INFORMATIONAL,
            local_only=True,
            description="a deterministic guided threat-response plan",
            priority=118,
        ),
        IntentDefinition(
            intent_id="security.threat.remediate.confirm",
            command_type="THREAT_REMEDIATE_CONFIRM",
            aliases=frozenset({"confirm defender remediation"}),
            risk=IntentRisk.HIGH_IMPACT,
            local_only=True,
            description="confirmation for guarded Defender remediation",
            priority=140,
        ),
        IntentDefinition(
            intent_id="security.threat.remediate",
            command_type="THREAT_REMEDIATE_REQUEST",
            actions=frozenset({"remediate", "neutralize", "remove"}),
            objects=frozenset({"threat", "detected threat", "defender threat", "malware"}),
            aliases=frozenset({"remediate threat", "review remediation", "remove defender threat", "neutralize detected threat"}),
            required_slots=("target_path",),
            risk=IntentRisk.HIGH_IMPACT,
            local_only=True,
            description="prepare guarded provider-native Defender remediation",
            priority=126,
        ),
        IntentDefinition(
            intent_id="security.threat.delete_blocked",
            command_type="THREAT_DELETE_BLOCKED",
            actions=frozenset({"delete", "erase", "destroy", "permanently remove"}),
            objects=frozenset({"threat file", "suspicious file", "malware file", "dangerous file"}),
            aliases=frozenset({"delete suspicious file", "delete threat file", "permanently delete malware"}),
            risk=IntentRisk.HIGH_IMPACT,
            local_only=True,
            description="Early Alpha permanent-file-deletion policy response",
            priority=128,
        ),
        IntentDefinition(
            intent_id="security.threat_center.show",
            command_type="THREAT_CENTER_SHOW",
            actions=frozenset({"show", "open", "list", "review"}),
            objects=frozenset({"threat center", "threat analyses", "security findings"}),
            aliases=frozenset({"show threat center", "open threat center", "list threat analyses"}),
            risk=IntentRisk.INFORMATIONAL,
            local_only=True,
            description="the local Threat Center summary",
            priority=109,
        ),
        IntentDefinition(
            intent_id="assistance.task_center.show",
            command_type="TASK_CENTER_SHOW",
            actions=frozenset({"show", "open", "list", "review"}),
            objects=frozenset({"task center", "background tasks", "assistance tasks"}),
            aliases=frozenset({"show task center", "open task center", "list background tasks"}),
            risk=IntentRisk.INFORMATIONAL,
            local_only=True,
            description="the durable assistance Task Center summary",
            priority=108,
        ),
    )
    for definition in definitions:
        registry.register(definition)
    return registry
